### ISSUE TITLE
Issue when using relative path for "metadata-file" option (and file is not in cwd)

### ISSUE THREAD

**Issue by bshaffer** [googleapis/docuploader#132]
The `metadata-file` option does not work as expected, and fails unless the file is in the CWD or an absolute path is used.

#### Environment details

  - Programming language: PHP
  - OS: MacOSX
  - Language runtime version:
  - Package version: 0.6.2

#### Steps to reproduce

  1. Put `docs.metadata` file in the CWD and run the command 
    ```
    docuploader upload out --staging-bucket docs-staging-v2-dev --destination-prefix docfx-
    ```
    This works as expected
  3. Now put `docs.metadata` in the `out` directory and specify the path but running:
    ```
    docuploader upload out --staging-bucket docs-staging-v2-dev --destination-prefix docfx- --metadata-file out/docs.metadata
    ```
    This results in the following error: `FileNotFoundError: [Errno 2] No such file or directory: 'out/out/docs.metadata'` (full stacktrace below)
  4. Now put JUST `docs.metadata` as the value for `--metadata-file` (maybe it expects the path to be relative to the output dir). This results in the following error:  `docuploader > You need metadata to upload the docs. You can generate it with docuploader create-metadata`
  5. Now supply the ABSOLUTE path to the option, OR move the `docs.metadata` file into the CWD and run with `--metadata-file docs.metadata`. That works as expected

#### Stack trace
```
docuploader upload out --staging-bucket docs-staging-v2-dev --destination-prefix docfx- --metadata-file out/docs.metadata 
docuploader > Let's upload some docs!
docuploader > Loading up your metadata.
Traceback (most recent call last):
  File "/Users/betterbrent/bin/docuploader", line 8, in <module>
    sys.exit(main())
  File "/Users/betterbrent/Library/Python/3.8/lib/python/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/betterbrent/Library/Python/3.8/lib/python/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/betterbrent/Library/Python/3.8/lib/python/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/betterbrent/Library/Python/3.8/lib/python/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/betterbrent/Library/Python/3.8/lib/python/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/betterbrent/Library/Python/3.8/lib/python/site-packages/docuploader/__main__.py", line 95, in upload
    shutil.copy(metadata_path, pathlib.Path(documentation_path) / metadata_file)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/shutil.py", line 418, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'out/out/docs.metadata'
```

**Comment by dandhlee** [comment]
I can see where this is going wrong - it does expect the metadata file to be relevant to the CWD; this is the bit that gets it awkward:

```
shutil.copy(metadata_path, pathlib.Path(documentation_path) / metadata_file)
```

in this case - we have `documentation_path` is `out` and `metadata_file` exists in the documentation path. Not ideal, but we can fix this :)

The documentation to reflect the fact that it should be relevant to CWD.
