### ISSUE TITLE
BUG: Failed docs jobs should not exit with status 0.

### ISSUE THREAD

**Issue by busunkim96** [googleapis/docuploader#20]
@tmatsuo reported that a failed docs job exited with status 0, making it appear the job had succeeded.

```
================================================================
Detecting version Fri Sep 13 07:32:42 PDT 2019.
================================================================
Creating docs metadata Fri Sep 13 07:32:42 PDT 2019.
Traceback (most recent call last):
  File "/home/kbuilder/.pyenv/versions/3.6.1/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/kbuilder/.pyenv/versions/3.6.1/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/kbuilder/.local/lib/python3.6/site-packages/docuploader/__main__.py", line 26, in <module>
    from docuploader.protos import metadata_pb2
  File "/home/kbuilder/.local/lib/python3.6/site-packages/docuploader/protos/metadata_pb2.py", line 28, in <module>
    dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR],
TypeError: __new__() got an unexpected keyword argument 'serialized_options'
```

**Comment by tmatsuo** [comment]
Oh wait, I tried to reproduce this, but seems like docuploader correctly exit with 1.

There must be another reason that the build was marked as green.

**Comment by tmatsuo** [comment]
Yeah I confirmed our build script had a bug. Sorry for the false alarm.
