### ISSUE TITLE
Fix failing lint sessions

### ISSUE THREAD

**Issue by dandhlee** [googleapis/docuploader#85]
Since August 22 the default py3.8 session for lint has been failing with 
```
ox > Command python -m pip install mypy flake8 black types-pkg_resources failed with exit code 1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/google/home/dandhlee/workspace/docuploader/.nox/lint/lib/python3.8/site-packages/pip/__main__.py", line 29, in <module>
    from pip._internal.cli.main import main as _main
  File "/usr/local/google/home/dandhlee/workspace/docuploader/.nox/lint/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/local/google/home/dandhlee/workspace/docuploader/.nox/lint/lib/python3.8/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/local/google/home/dandhlee/workspace/docuploader/.nox/lint/lib/python3.8/site-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/local/google/home/dandhlee/workspace/docuploader/.nox/lint/lib/python3.8/site-packages/pip/_internal/cli/cmdoptions.py", line 23, in <module>
    from pip._internal.cli.parser import ConfigOptionParser
  File "/usr/local/google/home/dandhlee/workspace/docuploader/.nox/lint/lib/python3.8/site-packages/pip/_internal/cli/parser.py", line 12, in <module>
    from pip._internal.configuration import Configuration, ConfigurationError
  File "/usr/local/google/home/dandhlee/workspace/docuploader/.nox/lint/lib/python3.8/site-packages/pip/_internal/configuration.py", line 27, in <module>
    from pip._internal.utils.misc import ensure_dir, enum
  File "/usr/local/google/home/dandhlee/workspace/docuploader/.nox/lint/lib/python3.8/site-packages/pip/_internal/utils/misc.py", line 42, in <module>
    from pip._internal.locations import get_major_minor_version, site_packages, user_site
  File "/usr/local/google/home/dandhlee/workspace/docuploader/.nox/lint/lib/python3.8/site-packages/pip/_internal/locations/__init__.py", line 14, in <module>
    from . import _distutils, _sysconfig
  File "/usr/local/google/home/dandhlee/workspace/docuploader/.nox/lint/lib/python3.8/site-packages/pip/_internal/locations/_distutils.py", line 9, in <module>
    from distutils.cmd import Command as DistutilsCommand
ModuleNotFoundError: No module named 'distutils.cmd'
```

not sure how this happened, but doesn't seem like it will resolve itself.

**Comment by dandhlee** [comment]
Fixed with #87!
